### ISSUE TITLE
add ssl certificate from letsencrypt

### ISSUE THREAD

**Issue by hadifarnoud** [modoboa/modoboa-installer#16] opened 2016-01-11 11:22 UTC
how can I activate letsencrypt.org certificate on modoboa?

would be great to add this into run.py

**Comment by tonioo** [comment] 2016-01-11 12:21
For now, you can only specify custom SSL certificates within the configuration file:
```ini
[general]
tls_key_file = /etc/ssl/private/ssl-cert-snakeoil.key
tls_cert_file = /etc/ssl/certs/ssl-cert-snakeoil.pem
```

**Comment by inkrement** [comment] 2016-03-11 16:55
How to proceed if it's intended to add certificates after installation? Is there a easy possibility without the need to dig into postfix or dovecot configs?

**Comment by tonioo** [comment] 2016-03-11 19:48
Modify the default values inside installer.cfg and then copy certificate files at the proper location.

**Comment by inkrement** [comment] 2016-03-11 19:51
The installer.cfg is part of the installer, right? But I have already installed it (and I removed the installation folder). How can I change these settings afterwards?

**Comment by tonioo** [comment] 2016-03-14 12:46
Then you need to modify each configuration file (postfix, dovecot, etc.).

**Comment by dhaupin** [comment] 2016-09-01 23:25
Really, all this needs is a pub .well-known folder somewhere to run and update later (via cron or something). Just tried LE and it wanted to work. I gotta pack for camping and dont have much time to probe modo this eve beyond breif tries, but before i go, how do we make a pub .well-known folder in the webroot? I think that would solve this since this is a google result.

I figured the root, or something like this would work plus or minus the sitestatic:

`letsencrypt certonly --webroot -w /srv/modoboa/instance/sitestatic/js -d host.example.com`

**Comment by dhaupin** [comment] 2016-09-02 16:06
Ok, I got a min, here is how you do a LE cert:

1) Create a `.well-known` folder:
`# mkdir /srv/modoboa/instance/sitestatic/.well-known`

2) Edit the port 80 server block to use this:

	server {
		listen 80;
		server_name mail.example.com;

		location / {
			rewrite ^ https://$server_name$request_uri? permanent;
		}

		location /.well-known/ {
			alias /srv/modoboa/instance/sitestatic/.well-known/;
		}
	}

3) Restart nginx then run the LE certonly:
`# letsencrypt certonly --webroot -w /srv/modoboa/instance/sitestatic/ -d mail.example.com`

4) Edit the port 443 server block to use new certs:

	...
	ssl_certificate /etc/letsencrypt/live/mail.example.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/mail.example.com/privkey.pem;
	...

5) Restart nginx, check the URL. Apply cert to any other services you need such as dovecot. SNI is possible, but beyond this scope.

6) Make a cron to auto-renew (`# crontab -e`), in this case at 5:43 am daily:
`43 5 * * * /usr/bin/letsencrypt renew 2>&1 | /usr/bin/logger -t letsencrypt`

7) Profit.

**Comment by hadifarnoud** [comment] 2016-09-03 07:21
please send a Pull Request for this feature. would love to try it

**Comment by dhaupin** [comment] 2016-09-07 20:32
@hadifarnoud Would like to man, not much time lately though. I would have to further explore the installer itself, figure out how to check for a fail state if LE can't generate a cert or times out, and also support SNI based on added domain(s). Maybe it can be a "standalone" plugin or something instead of at install, dunno. Added a few steps for Dovecot/Postfix above.

**Comment by tonioo** [comment] 2016-09-21 13:59
@dhaupin Thanks you for the feedback. I close this issue since it's a duplicate of #50 .

**Closed by tonioo** 2016-09-21 13:59 UTC

**Comment by dbryar** [comment] 2020-08-15 07:38
since this is the highest ranked page on LE certificate errors on Google, I'll just point out that while @dhaupin instructions are all correct, if you are using LE, you may need to reboot the server/restart the services after the new certificate is loaded each 90 day period. 

I was finding it very hard to determine why the mail server (postfix) was still issuing an expired certificate despite the webmail (nginx) certificate being valid, and both pointing to the same file.

Something to note on very stable servers!

**Comment by blu-IT** [comment] 2021-03-18 14:29
>     2. Edit the port 80 server block to use this:
> 
> 
> ```
> server {
>     listen 80;
>     server_name mail.example.com;
> 
>     location / {
>         rewrite ^ https://$server_name$request_uri? permanent;
>     }
> 
>     location /.well-known/ {
>         alias /srv/modoboa/instance/sitestatic/.well-known/;
>     }
> }
> ```
> 

Thanks a lot! Worked perfect for me, after that I had already rolled out the server with a self-signed certificate accidently!
Had only to **add these lines also to the already existing config for port 443:** Then I could start LE certification process.
Working on Ubuntu 18.04 LTS

```
location /.well-known/ {
         alias /srv/modoboa/instance/sitestatic/.well-known/;
     }

**Comment by QThans** [comment] 2024-04-06 07:58
> 5\. /etc/dovecot/conf.d/10-ssl.conf

After updating, a restart is required.
