### ISSUE TITLE
Appropriate installation instructions would be nice

### ISSUE THREAD

**Issue by cringer** [modoboa/modoboa-installer#106] opened 2017-03-05 01:30 UTC
Installation says the recommended way is with this installer.  However, when following the instructions it says `sudo ./run.py <mail server hostname>`

So if i run this (yes I'm filling in my hostname where appropriate) I get an error stating `/usr/bin/env: ‘python’: No such file or directory`

This is a fresh install of Ubuntu 16.04.2 and when I run `python3 -V` it tells me `Python 3.5.2`
I imagine that the installer is looking for `python` and not `python3` but I have no idea how to change this.

**Comment by tonioo** [comment] 2017-03-05 08:50
That's strange because if python3 is the only installed version, then it should be also called python... To fix this, just install python2 (don't know the package name).

**Comment by tonioo** [comment] 2017-03-17 08:19
@cringer Any news about this?

**Comment by almereyda** [comment] 2017-04-08 11:08
This is probably also a duplicate of #38 and needs to be considered there, too. Else I suggest renaming this issue to *Ubuntu 16.04.2 : missing python dependency".

**Comment by nklamann** [comment] 2017-08-24 10:09
I was not aware that the installer by itself  prepends 'mail.' to the given domain . I consider this a reasonable default but i entered 'mail.domain.name' as domain name and it produced 'mail.mail.domain.name'.

This should be mentioned, even in the homepage

**Comment by mylastore** [comment] 2017-09-04 23:51
after a successful install what are the urls?

**Closed** 2018-03-09 14:34 UTC
