### ISSUE TITLE
Installer Fails (Install Dir)

### ISSUE THREAD

**Issue by lesichkovm** [modoboa/modoboa-installer#101] opened 2017-02-11 10:32 UTC
Changed install dir path to /mail

> Installing modoboa
> Traceback (most recent call last):
>   File "./run.py", line 73, in <module>
>     main()
>   File "./run.py", line 63, in main
>     scripts.install("modoboa", config)
>   File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", li       ne 21, in install
>     getattr(script, appname.capitalize())(config).run()
>   File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 1       51, in run
>     self.post_run()
>   File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", lin       e 173, in post_run
>     self.apply_settings()
>   File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", lin       e 148, in apply_settings
>     utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
>   File "/root/modoboa-installer/modoboa_installer/utils.py", line 79, in m       kdir
>     os.mkdir(path, mode)
> OSError: [Errno 2] No such file or directory: '/mail/instance/media/webmai       l'

**Comment by tonioo** [comment] 2017-02-13 08:31
Have you seen this error before or after #100?
Can you try from scratch using the --debug option please?

**Comment by lesichkovm** [comment] 2017-02-13 18:31
It was after #100, I changed the password, deleted the whole VPS box, and started from scratch. Then is when the error showed up.

**Comment by tonioo** [comment] 2017-02-14 10:44
I really need a trace otherwise I can't help you.

**Comment by nrotschafer** [comment] 2017-02-25 04:30
Ok so I ran into the same issue and can effectively tell you the issue is that the installer doesn't verify that mysql-client and mysql-devel (or mariadb) are installed BEFORE it tries to install mysql-python.

**Comment by nrotschafer** [comment] 2017-02-25 05:35
The issue after that was installing mysql-python and that had to do with openssl-devel not being installed...so it seems like there is some lack of dependency checking in the installer that really needs to be resolved!

**Comment by tonioo** [comment] 2017-02-26 16:11
MySQL/MariaDB and development libs are installed by the installer unless you disable it. Have you modified the configuration file? On which distribution are you deploying modoboa?

**Comment by tonioo** [comment] 2017-02-27 08:28
@lesichkovm Why did you close the issue?

**Closed** 2017-02-27 08:28 UTC
Labels: enhancement, need more information
